{"name": "Если авторизоваться под несуществующим пользователем, запрос возвращает ошибку", "status": "passed", "start": 1728216687001, "stop": 1728216687111, "uuid": "6271f2af-1374-4394-bad5-3c6e1e6056e0", "historyId": "ca609b376c8df0d6336f167288c3af7e", "testCaseId": "ca609b376c8df0d6336f167288c3af7e", "fullName": "tests.test_login_courier.TestCreateLogin#test_login_wrong_data_error_success", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestCreateLogin"}, {"name": "host", "value": "WIN-4TEUO1LLUHP"}, {"name": "thread", "value": "292-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}