{"name": "Если авторизоваться под несуществующим пользователем, запрос возвращает ошибку", "status": "passed", "start": 1728216723018, "stop": 1728216723143, "uuid": "dc0cabaa-7586-449b-bdae-bac98eec9247", "historyId": "ca609b376c8df0d6336f167288c3af7e", "testCaseId": "ca609b376c8df0d6336f167288c3af7e", "fullName": "tests.test_login_courier.TestCreateLogin#test_login_wrong_data_error_success", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestCreateLogin"}, {"name": "host", "value": "WIN-4TEUO1LLUHP"}, {"name": "thread", "value": "29512-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}