{"name": "Если авторизоваться под несуществующим пользователем, запрос возвращает ошибку", "status": "passed", "start": 1728216458750, "stop": 1728216458844, "uuid": "64bdd628-2728-442e-8e21-546aa3e03c85", "historyId": "ca609b376c8df0d6336f167288c3af7e", "testCaseId": "ca609b376c8df0d6336f167288c3af7e", "fullName": "tests.test_login_courier.TestCreateLogin#test_login_wrong_data_error_success", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestCreateLogin"}, {"name": "host", "value": "WIN-4TEUO1LLUHP"}, {"name": "thread", "value": "29800-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}