{"name": "Если авторизоваться под несуществующим пользователем, запрос возвращает ошибку", "status": "passed", "start": 1728250379390, "stop": 1728250379515, "uuid": "630f2862-0519-4711-96bc-a9b1afeaeda9", "historyId": "ca609b376c8df0d6336f167288c3af7e", "testCaseId": "ca609b376c8df0d6336f167288c3af7e", "fullName": "tests.test_login_courier.TestCreateLogin#test_login_wrong_data_error_success", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestCreateLogin"}, {"name": "host", "value": "WIN-4TEUO1LLUHP"}, {"name": "thread", "value": "13788-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}